name: PlaytimeRoles
version: 1.0.0
main: com.example.playtimeroles.PlaytimeRolesPlugin
api-version: 1.21
depend: [LuckPerms]

commands:
  playtime:
    description: Показать время игры
    usage: /playtime [игрок]
    permission: playtimeroles.playtime
